import esbuild from 'esbuild';

const buildConfig = {
  entryPoints: ['src/index.ts'],
  bundle: true,
  platform: 'browser',
  target: 'es2020',
  format: 'esm',
  outExtension: { '.js': '.js' },
  external: [],
  sourcemap: false,
  minify: true,
  keepNames: true,
  define: {
    'process.env.NODE_ENV': '"production"',
    global: 'globalThis',
  },
  alias: {
    // Only the modules actually used in the source code
    path: 'path-browserify',
    'node:path': 'path-browserify',
    'node:buffer': 'buffer',
    'node:events': 'events',
    'node:stream': 'stream-browserify',
    // For dependencies that need HTTP modules
    http: 'stream-http',
    https: 'https-browserify',
    querystring: 'querystring-es3',
  },
  banner: {
    js: `// legit-sdk library bundle\n// Generated by esbuild\n`,
  },
};

// Build function
async function build() {
  try {
    console.log('Building legit-sdk library...');

    // Browser build - bundle everything
    await esbuild.build({
      ...buildConfig,
      outfile: 'dist/legit-sdk.js',
    });

    console.log('✅ Build completed successfully!');
    console.log('📦 Output files:');
    console.log('  - dist/legit-sdk.js (Browser ESM - everything bundled)');
    console.log('  - dist/legit-sdk.js.map (Source map)');
  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}

// Run build if this file is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  build();
}

export { build, buildConfig };
