import esbuild from 'esbuild';

const buildConfig = {
  entryPoints: ['src/index.ts'],
  bundle: true,
  platform: 'browser',
  target: 'es2020',
  format: 'esm',
  outExtension: { '.js': '.js' },
  // Do not bundle peer deps; let consumers install them
  external: ['react', 'react/jsx-runtime', '@legit-sdk/core', 'memfs'],
  sourcemap: false,
  minify: true,
  keepNames: true,
  define: {
    'process.env.NODE_ENV': '"production"',
    global: 'globalThis',
  },
  banner: {
    js: `// @legit-sdk/react bundle (ESM)\n// Generated by esbuild\n`,
  },
};

async function build() {
  try {
    console.log('Building @legit-sdk/react...');
    await esbuild.build({
      ...buildConfig,
      outfile: 'dist/index.js',
    });
    console.log('✅ Build completed');
  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  build();
}

export { build, buildConfig };
