import esbuild from 'esbuild';

const buildConfig = {
  entryPoints: ['src/index.ts'],
  bundle: true,
  platform: 'node',
  target: 'es2020',
  format: 'esm',
  outExtension: { '.js': '.js' },
  // Do not bundle peer deps; let consumers install them
  external: ['react', 'react-dom', 'react/jsx-runtime', '@assistant-ui/react'],
  sourcemap: false,
  minify: true,
  keepNames: true,
  define: {
    'process.env.NODE_ENV': '"production"',
    global: 'globalThis',
  },
  banner: {
    js: `// @legit-sdk/assistant-ui bundle (ESM)\n// Generated by esbuild\n`,
  },
  alias: {
    '@legit-sdk/core': '@legit-sdk/core/server', // CSR maps to client
  },
};

async function build() {
  try {
    console.log('Building @legit-sdk/assistant-ui...');
    // Build main bundle (with React)
    await esbuild.build({
      ...buildConfig,
      outfile: 'dist/index.js',
    });
    // Build server bundle (no React)
    await esbuild.build({
      ...buildConfig,
      entryPoints: ['src/server.ts'],
      platform: 'node',
      outfile: 'dist/server.js',
    });
    console.log('✅ Build completed');
  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  build();
}

export { build, buildConfig };
